# .github/workflows/deploy.yml
name: Deploy to Koyeb

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          python -m pytest tests/ -v
          
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Koyeb
        uses: koyeb-community/koyeb-action@v2
        with:
          api_token: ${{ secrets.KOYEB_TOKEN }}
          app: ad-request-tracker
          service: api
          # Puedes especificar la región
          # region: fra