name: ad-request-tracker
services:
  - name: api
    image: koyeb/app:ad-tracker
    ports:
      - port: 8000
        http: / 
    env:
      - name: DATABASE_URL
        value: postgresql://user:pass@db-host:5432/ad_tracker
      - name: GOOGLE_API_KEY
        secret: google-api-key
      - name: SECRET_KEY
        generate: "hex(32)"
    regions:
      - fra  # Frankfurt
    instance:
      type: nano
    scaling:
      min: 1
      max: 3
    routes:
      - path: /
        port: 8000
    
  # (Opcional) Base de datos PostgreSQL
  - name: database
    image: postgres:15
    env:
      - name: POSTGRES_DB
        value: ad_tracker
      - name: POSTGRES_USER
        value: admin
      - name: POSTGRES_PASSWORD
        secret: db-password
    volumes:
      - name: pgdata
        path: /var/lib/postgresql/data
    ports:
      - port: 5432
        protocol: postgresql